apiVersion: v1
kind: ReplicationController
metadata:
  name: "helloworld"
spec:
  replicas: 2
  selector:
    name: helloworld
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: "339936612855.dkr.ecr.us-east-1.amazonaws.com/helloworld:v0.1.2"
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80