apiVersion: apps/v1
kind: Deployment
metadata:
  name: "helloworld"
spec:
  replicas: 2
  selector:
    matchLabels:
      name: helloworld
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: "339936612855.dkr.ecr.us-east-1.amazonaws.com/helloworld:v1.4.0"
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80